### PR TITLE
Development

### PR DESCRIPTION
**Pull request by deborahvandervegt**
* Run symfony and PSR-2 codings standards fixer on addon
* Rewrite handleMode in module to replace switch / case for if / else so it's better readable
* Added extra criteria to overview to show only active activities
* Moved isOpen() to activities plugin since it's requested there

### CODE REVIEW

**Comment by RonRademaker** [comment]
Looks like this is multiple things pushed into one PR, which makes reviewing harder than necessary. Could explain what this should do?

**Comment by deborahvandervegt** [comment]
Making a branch and PR for every change separately while addon is still in development mode is very time consuming. Bottom line of this PR is: 

- Run symfony and PSR-2 codings standards fixer on addon
- Rewrite handleMode in module to replace switch / case for if / else so it's better readable
- Added extra criteria to overview to show only active activities
- Moved isOpen() to activities plugin since it's requested there

Most important is handleMode and overviewCriteria in the module, can you review them? The rest are code style fixers and ufnames.

**Comment by RonRademaker** [comment]
Yes, I'll review those parts. It'll take time to get used to, but try to make PRs for different functionalities and describe what you did, also make an issue before you start making something describing what you're going to do. Choose better names for your PRs as well, *development* is a bit vague.

Of course you don't have to put every rewrite / refactor in a PR of its own. You can combine a lot of things that belong together, a complete userstory can be one single PR. Try to develop a one complete functionality in a PR.

**Comment by RonRademaker** [comment]
You could make ```handleMode``` more readable and testable by creating small functions for the different situations instead of moving it from a switch-case to if-elseif statements.

**Pull request merged**
